# 20251027.000

# added support for jira project keys to be defined per tenant
# based on contents within an attribute field within the tenant properties within stellar
# if this field is populated, the "jira_project_key" value above is ignored
# and the value of this field is the field name where the project key will be read from
# value fields are: address, contact (prefereably address)
# if the value below is populated, only tenants that have a value within the selected attribute will be sync'd
# in other words, leave the "address" field blank in tenants to not have them sync to jira tickets
per_tenant_project_key_field: "address"

# jira attributes

# ignore if using per tenant project key fields
jira_project_key: "STIP"

# type of issue to open
#jira_issue_key: "Security Event"
jira_issue_type: "Incident"

# polling interval in minutes for new cases and case to issue sync
stellar_poll_interval: 1

# tag to add to stellar cases once opened in jira
stellar_case_tag: "jira_issue_opened"

# when stellar opens a jira issue, this string will be prefixed to the case name
# leave blank or comment out to omit
subject_prefix: "StellarCyber Alert: "

# list of stellar tenants to filter in
# if commented out, then cases from all tenants will be included
#tenant_filter:
#  - "azure_ad_riskyuser"
#  - "another tenant"

# KEY VALUES are used as the jira priority name (evidently case-sensitive) and must match those used by JIRA
# They are listed in the order they are processed/checked against the case score
#  - if case score is greater than the "min" value, then it is considered a match and processing stops
# IDs are ignored placeholders for now, as are hours
SLA:
  Critical:
    min: 90
    hours: 2
    jira_priority: 1
  High:
    min: 75
    hours: 6
    jira_priority: 2
  Medium:
    min: 19
    hours: 48
    jira_priority: 3
  Informational:
    min: 1
    hours: 72
    jira_priority: 4

####################
#
# JIRA SYNC

# set true to have jira comments sync'd back to stellar
sync_jira_comments: false

# sync comments by querying the jira servicedesk api (which contains a a "public" key for internal or external comments)
jira_comments_use_servicedesk_api: true

# sync only "internal", "public", or leave empty/comment out for all jira comments back to stellar
# (servicedesk api must be true to set internal or public)
jira_comments_filter: "internal"

# set true to have jira assignees added as a stellar case comment
add_jira_assignee_to_comment: true

# set to true to sync the jira priority back to the stellar case when jira priority changes
sync_jira_priority: true

# set to true to sync the jira resolved state back to the stellar case
# defaults to true
sync_jira_state_resolved: true

# set to true to sync the jira in progress state back to the stellar case
# defaults to false
sync_jira_state_inprogress: true

# set to true to sync the jira in reopened state back to the stellar case
# defaults to false
sync_jira_state_reopen: true

# the jira <-> stellar priority mapping when the jira priority sync is set to true (above)
# jira priority: stellar severity (critical, high, medium, low)
jira_priority_map:
  "Critical": "Critical"
  "High": "High"
  "Medium": "Medium"
  "Low": "Low"
  "Informational": "Low"

# custom jira fields
# for now - any fields below will populate with a date value (e.g.: "2024-10-03")
# get the field id by using the get_issue_fields method and grep for the field name
#custom_field: "customfield_10015"

####################
#
# STELLAR SYNC

# upon creation of a new jira ticket, set the stellar status to this value
# can be one of "Escalated", "New", "In Progress", "Resolved", Cancelled"
# leave empty or comment out for no change (stellar case will stay NEW)
stellar_case_status_upon_initial_sync: ""

# set to true to sync stellar comments to the jira issue
sync_stellar_comments: false

# set to true to sync updates to a stellar case (score, new alerts) to the jira issue as a comment
sync_stellar_case_updates: true

# set to true to have stellar comments or updates tagged as public, which means they will be exposed to external parties and receive notifications
# if set to false, the comments are tagged internal which hides the comment from external parties and disables notifications
# defaults to true
sync_stellar_comments_as_public: false

# enter the name of the jira resolved state in order to sync the stellar case resolution back to jira
# leave blank or comment out to disable
# resolved types, such as Benign, False Positive, True Positive will also sync if there is a match
# see transitions: /rest/api/2/issue/{issue key}/transitions
# see resolutions: /rest/api/2/resolution
sync_stellar_status_resolved: "Resolved"
stellar_case_resolutions:
  "Benign": "Benign"
  "False Positive": "False Positive"
  "True Positive": "True Positive"
  "Default": "Benign"

# enter the name of the jira reopened state in order to sync the stellar case New back to jira
# leave blank or comment out to disable
sync_stellar_status_reopened: "Open"

# enter the name of the jira in progress state in order to sync the stellar case In progress or Escalated back to jira
# leave blank or comment out to disable
sync_stellar_status_inprogress: "In Progress"

# sync the stellar assignee to a jira comment
sync_stellar_assignee_to_jira_comment: true






